version: "3.8"

services:
  tictactoe:
    image: tic-tac-toe
    ports:
      - "8080:5000"          # host 8080 -> container 5000
    deploy:
      replicas: 1            # Reduced from 3 to 1 due to database connection limit
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3z
      update_config:
        parallelism: 1
        order: start-first
        delay: 3s
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:5000/ || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  prometheus: 
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure # Prometheus section ONLY, done by Eleanor 

#Done by Bryan
